### ISSUE TITLE
元リポジトリ `OfficeDev/microsoft-teams-apps-company-communicator` の `v4.1` の更新取込みについて

### ISSUE THREAD

**Issue by dzeyelid** [OfficeDevJP/microsoft-teams-apps-company-communicator#3]
本リポジトリの `v1.0.0` のリリース以降、元リポジトリで下記が更新されています。

- 元リポジトリ OfficeDev のリリース [`v4.1`](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/releases/tag/v4.1) に含まれる変更
  - OfficeDev/microsoft-teams-apps-company-communicator#393
  - OfficeDev/microsoft-teams-apps-company-communicator#394

ご確認の上、必要に応じてご対応ください。

**Comment by osamum** [comment]
ご報告ありがとうございます。
元リポジトリの変更内容を確認し、さらにローカルで元リポジトリのpackage-lock.jsonとJP側の diff を取って変更箇所が間違いないことを再度確認のうえファイルを更新しました。
とはいえ、JP 側のリポジトリに以前のファイルとの diff が出ないので、次回からはやり方を変えようと思います。
